name: Generate Samples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-samples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate samples
        run: python3 generate_samples_md.py

      - name: Check for uncommitted changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Uncommitted changes to README.md/SAMPLES.md detected. Please commit the changes."
            exit 1
          fi
