name: Verify Mule Docs
on:
  push:
    branches:
      - main
      - dev-3.x
  pull_request:
    branches:
      - main
      - dev-3.x

jobs:
  generate-samples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Mule v3 docs
        run: python3 scripts/generate_mule_docs_v3.py

      - name: Generate Mule v4 docs
        run: python3 scripts/generate_mule_docs_v4.py

      - name: Print git diff
        run: git diff

      - name: Check for uncommitted changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Uncommitted changes to README.md and documentation files detected. Please commit the changes."
            exit 1
          fi
